server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/piaps
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.web: info
