server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/piaps
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

app:
  seed:
    enabled: true
    key: main-data-v1
    script: classpath:data.sql

logging:
  file:
    name: piaps.log
  level:
    org.hibernate.SQL: warn
    org.springframework.web: info
