server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/piaps
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

app:
logging:
  level:
    ru.university.piaps: info
    org.hibernate.SQL: warn
    org.springframework.web: info
